sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t asalad42/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asalad42/docker-react npm run test
